### ISSUE TITLE
[Android] The “Add files(s)” icon, text and total file size are wrongly cut when multiple files are added 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1143]
**[Affected Platforms]:**
- Android 8.0 (Samsung S8, Google Pixel, Huawei P20 Lite)

**[Prerequisites]:**
- Have the latest Send Android build (org.mozilla.sendandroid-2019-02-06-signed.apk)

**[Steps to reproduce]:**
1. Open the Send Android application.
2. Tap the “Add file(s)” button and add over 10 files.
3. Observe the “Add file(s)” button.

**[Expected result]:**
- The “Add file(s)” button’s icon, text and total file size are fully visible.

**[Actual result]:**
- The top part of the “Add files(s)” icon, text and total file size are not visible.

**[Notes]:**
- This issue is not reproducible with the previous Send Android builds.
- The more files you have added the more is cut from the “Add file(s)” icon and text. See the screenshot: 

![screenshot_20190208-121222_send android](https://user-images.githubusercontent.com/37875464/52475652-c4544a00-2ba4-11e9-964b-c676c49fc5f6.jpg)

- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1W44nwOVr8m4RSBZnbFtplhwOeJizvCc4)

**Comment by dannycoates** [comment]
I _think_ this is fixed as of c1df061669cf2c565b90cfbe818ae004a5d5adc7

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is still reproducible with the latest build (org.mozilla.sendandroid-2019-02-20-release-signed.apk) on Samsung S8, Huawei P20 Lite and Google Pixel(Android 8.0).

Considering this I will reopen this issue.

**Comment by fzzzy** [comment]
That's odd. It's fixed on my s8. Will investigate further.

**Comment by Softvision-AndreeaCupsa** [comment]
What Android version do you have on your device? We didn't update our Samsung S8 to Android 9, so it's still on Android 8.0.0.

**Comment by fzzzy** [comment]
8.0.0.

**Comment by johngruen** [comment]
@Softvision-AndreeaCupsa does this still repro on the latest build

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Android Send version (org.mozilla.sendandroid-2019-03-01-release-signed.apk) and the issue is still reproducible.
But, it seems that is more visible if you try to add more then 15 files. 

Here are two screenshots of the issue with 20 files added:
Samsung S8 (Android 8.0.0):
![screenshot_20190305-120119_send android](https://user-images.githubusercontent.com/19226534/53805850-f6fb2380-3f53-11e9-88be-3980d014555b.jpg)

Google Pixel (Andriod 8.0.0):
![screenshot_20190305-120326](https://user-images.githubusercontent.com/19226534/53805851-f95d7d80-3f53-11e9-9d91-20c906ec7a1a.png)

**Comment by dannycoates** [comment]
thanks @SoftVision-CosminMuntean adding a bunch of files helped me reproduce. fixed in d25c411
