### ISSUE TITLE
[Mac OS] Download option still displayed for expired file after browser restart

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#159]
[Notes]:
- A similar behavior can be observed if the browser is restarted right after downloading a file. Instead of the 404 page, the download card will be displayed.

[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Mac

[Prerequisites]:
- "When Firefox starts: Show my windows and tabs from last time" option is set in about:preferences

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file and open the download link in two different tabs.
3. Download the file in the first tab and then navigate to the second tab.
4. Close the browser (Quit) and reopen it with the same profile.
5. Observe the displayed tab.

[Expected result]:
- The "Link expired" page is displayed.

[Actual results]:
- The Download card is displayed.

[Additional notes]:
- This issue is also reproducible on the stage page (https://send.stage.mozaws.net). 
- If the page is manually refreshed, the "Link expired" page is correctly displayed.
- Here is a screen recording with the issue: [Link](https://drive.google.com/open?id=0B8ICzPJynbchSlI1MFVGQUlCUDA).

**Comment by SoftVision-CiprianMuresan** [comment]
This issue is now reproducible on Windows and Linux too.

**Comment by dannycoates** [comment]
fixed in #297

**Comment by SoftVision-CiprianMuresan** [comment]
This issue is still reproducible on all platforms. Moreover after clicking the "Download" button for an expired link the download page is somehow merged with the Link expired page.

<img width="1280" alt="screen shot 2017-07-25 at 16 08 24" src="https://user-images.githubusercontent.com/18304511/28573642-ec807e5c-7153-11e7-82fc-21c36824a02a.png">

Screen recording: [here](https://drive.google.com/open?id=0B8ICzPJynbchcGRVdG9OZmI0TWM).

**Comment by dannycoates** [comment]
Any link created before about 2pm PST yesterday (24th) will have this behavior

**Comment by dannycoates** [comment]
The weird mixed error/download screen is fixed in #310. 

Having the page show that the link is expired immediately after a browser restart is difficult because the page is served from the browser cache, so we'd need to make an xhr request to check the status, which seems excessive given its rarity.
