### ISSUE TITLE
[Windows][Intermittent] Trying to upload folders does not trigger the dialog 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#332]
[Affected versions]:
- Firefox 54 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Create a folder in which you have 3 files.

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.dev.mozaws.net/" page.
2. Drag and Drop the folder from prerequisites in the Drop area.
3. Observe the behavior.

[Expected result]:
- "Can't upload multiple files or folder" dialog appears.

[Actual results]:
- "Something went wrong!" page is displayed.

[Additional notes]:
- Here is a screen recording of the issue:
![uploading folders does not work](https://user-images.githubusercontent.com/18304511/28674174-5186bf56-72ed-11e7-995f-5bbe04f01059.gif)

- When this occurs this is what is logged in the Browser Console:
![image](https://user-images.githubusercontent.com/18304511/28674285-a38d22fe-72ed-11e7-8a7b-b849c76f9f74.png)

**Comment by dannycoates** [comment]
we don't support drag&drop folders yet but the error is fixed in vnext

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is still reproducible on the https://send2.dev.lcip.org website.
 
Dragging and dropping a folder will not display an error message. Some folders are added and the "Something went wrong!" page is displayed after clicking the "Upload" button.

Attached a screen recording with the issue:

![rec of issue - folder](https://user-images.githubusercontent.com/37875464/51387503-e2db9e00-1b2e-11e9-9249-984d1cf5a978.gif)
