### ISSUE TITLE
[Send v2] The archived file is wrongly uploaded each time when the "Sending..." button is clicked

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#927]
[Notes]:
- The issue is also reproducible when you download an uploaded file. If you click multiple times on the "Downloading..." button, the file is downloaded for each click.

[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/ website.
2. Select or drag any file.
3. Click the "READY TO SEND" button.
4. Click multiple times the "Sending ..." button.
5. Observe the behavior.

[Expected result]:
- Nothing happens, the file continues to upload.

[Actual results]:
- A new upload starts for each click.

[Additional Notes]:
- Here is a screen recording when a file is uploaded:
![sending button](https://user-images.githubusercontent.com/19226534/45692533-ab022100-bb63-11e8-97c4-430c9ebc73b1.gif)

- Here is a screen recording when a file is downloaded:
![downloading button](https://user-images.githubusercontent.com/19226534/45692536-ad647b00-bb63-11e8-9f9f-0ac1088535df.gif)

**Comment by dannycoates** [comment]
This should be fixed on send2

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the Send v2 dev website and the issue is no longer reproducible when a file is uploading.

Unfortunately, the issue is still reproducible when a file is downloading. 
[Prerequisites]
- Have a link of an uploaded file.

[Steps to reproduce]:
1. Open the Firefox browser and navigate to the link from prerequisites.
2. Click the "Download" button.
3. Click multiple times the "Downloading..." button.
4. Observe the behavior.

[Expected result]:
- Nothing happens, the file continues to download.

[Actual results]:
- You are redirected to the "Something went wrong page" and the file starts to download for each click.

[Additional Notes]:
- Here is a screen recording when a file is downloaded:
![download](https://user-images.githubusercontent.com/19226534/45810665-d1df6500-bcd3-11e8-9768-cd5d1fa92867.gif)

**Comment by dannycoates** [comment]
fixed

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the Senv v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
